spring:
  server:
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: true

  application:
    name: uttarakhand


  ## Database Setup
  datasource:
#    url: jdbc:mysql://{IP_ADDRESS_OF_DATABASE}:{PORT_NUMBER}/{Database_Name}
#    username: {USERNAME_OF_DATABASE}
#    password: {PASSWORD_OF_DATABASE}
#    driver-class-name: {ADD_DRIVER_CLASS_NAME}  # For Mysql add this com.mysql.cj.jdbc.Driver
#
    url: jdbc:mysql://localhost:3306/registration
    username: root
    password: 8920611534
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


## Email Sender Setup
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000