server:
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: true

  application:
    name: uttarakhand
  datasource:
    url: jdbc:mysql://localhost:3306/registration jdbc:mysql://{ip_address}:{port}/{database_name}
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000