spring:
  server:
  error:
    include-message: never
    include-binding-errors: never
    whitelabel:
      enabled: false
  application:
    name: uttarakhand
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: ${EMAIL_SENDER_URL}
    port: ${EMAIL_SENDER_PORT}
    username: ${EMAIL_SENDER_USERNAME}
    password: ${EMAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
